import CommonLayout from "@/components/client-view/common-layout";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shakil Ahmed",
  description: "Generated by create next app",
};
{
  /* <meta name="keywords"
content="abdul moqueet, portfolio, full stack developer, moqueet, github.com/abdulmoqueet, abdul moqueet github">
<meta name="author" content="Abdul Moqueet"> */
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CommonLayout>{children}</CommonLayout>
      </body>
    </html>
  );
}
